type DashboardTableType = {
  dntShowExportDrop?: boolean;
  newBtnOpen?: boolean;
  exportDropOpen?: boolean;
  onOpenBtnChange?: () => void;
  onExportChange?: () => void;
  open?: boolean;
  handleOpenChange?: () => void;
  data: any;
  columns: any;
  searchVal?: string;
  onSearchChange?: (any) => void;
  href?: string | href;
  header?: string;
  isFilterDrop?: boolean;
  filterOptions?: string[];
  showTopHeader?: boolean;
  onManualBtn?: () => void;
  onBulkUploadBtn?: () => void;
  onPdfChange?: () => void;
  onCsvChange?: () => void;
  handleSearchClick?: () => void;
  isLoading?: boolean;
  searchData?: any;
  filterCheck?: any;
  filterOnCheck?: any;
  onCreateNewBtn?: () => void;
  onSelectTemplateBtn?: () => void;
  isMissionBtn?: boolean;
  dntShowNewBtn?: boolean;
};
